// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeDEc_wQFlqkLI0NOFr3_O60_1HGvI-9s',
    appId: '1:849154690981:web:c5b927e82aa39ff29c624c',
    messagingSenderId: '849154690981',
    projectId: 'posts-a0d8a',
    authDomain: 'posts-a0d8a.firebaseapp.com',
    storageBucket: 'posts-a0d8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBETMnyvhnrYmaXxCwEJRKjOa0QSBaMw',
    appId: '1:849154690981:android:e82fb9a974cb2fa59c624c',
    messagingSenderId: '849154690981',
    projectId: 'posts-a0d8a',
    storageBucket: 'posts-a0d8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMv20pcakobsI2fGF9Ro0cGfinG8do0Y',
    appId: '1:849154690981:ios:68e40132b8497eab9c624c',
    messagingSenderId: '849154690981',
    projectId: 'posts-a0d8a',
    storageBucket: 'posts-a0d8a.firebasestorage.app',
    iosBundleId: 'com.example.posts',
  );
}
